name: Collecter les signatures

on:
  schedule:
    - cron: '0 * * * *'  # Exécute le scraper toutes les heures
  workflow_dispatch:      # Permet de lancer manuellement

permissions:
  contents: write         # Donne les droits d'écriture au GITHUB_TOKEN

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dépôt
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Installer Python et dépendances
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Lancer le script de scraping
        run: python scraper.py

      - name: Commit et push des données
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "Mise à jour des signatures [skip ci]" || echo "Rien à committer"
          git pull --rebase origin main
          git push origin HEAD:main
