name: Collecter les signatures

on:
  schedule:
    - cron: '*/30 * * * *' # toutes les 30 minutes
  workflow_dispatch:       # permet de lancer manuellement

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Python + dépendances
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Lancer le script de scraping
        run: python scraper.py

      - name: Commit et push des données
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "Mise à jour automatique des données"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
